### PR TITLE
Use the correct node ID when removing the tree item from the cache

### LINKED ISSUE #506: Tree component's treeItemCache is not discarding nodes removed in deltas
**Describe the bug**

@oliver-sanders found that there was a memory leak, obvious after leaving a workflow running overnight. I reproduced it this morning after running `five` for a couple hours with development & product builds, and inspecting memory heap sampling and allocation in Chromium.

image

~`five` keeps only two cycle points in the UI. There are several in this `Map`, which doesn't show the `CylcTree` code, but I am 99.9999% certain that that is `CylcTree`'s lookup map (being the only map I am aware that holds ID's of job/cyclepoint/workflow/etc as key value).~

Turns out it was actually `treeItemCache` in `Tree` component.

image

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Run `five` for >10 minutes, and take a couple snapshots. Compare memory heap size, and compare objects in heap between the two snapshots. Then look for detached. Looking at the retainers panel, you should find the reference to the lookup table.

**Expected behavior**

Proper memory garbage-collected and without growing exponentially over time.

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by kinow**
These changes close #506 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (unit and/or functional).
- [x] No changelog required (was not part of the last release).
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Found the issue, which looks simple to fix. But pending:

- [ ] test it and confirm the fix works in the morning, after :coffee: to make sure I'm not missing anything else
- [ ] confirm the other caches in that component are being updated correctly
- [ ] check if this was released in the alpha2, if so, add a changelog
- [ ] check if it would be possible to write a unit test to cover the cache operations (add/remove)

**Comment by kinow** [comment]
After running the UI for ~15 minutes, **no detached elements in the UI**! :tada: 

image

**Comment by kinow** [comment]
All done! Reviewing can be done with browser development tools, or by leaving a workflow running for a long period of time :+1: 

This PR addresses memory leaks in caches. The rest of the application looks OK, so we should be good with memory management. Easier to test with the production build, maybe in an incognito browser to avoid issues with extensions.

**Review by oliver-sanders — APPROVED** [review]
Learning a bit about profiling 👍.

Comparing snapshots I was able to see detached SVG elements before but not after the change.

I did spot a few other detached elements kicking about:

Screenshot 2020-10-01 at 11 19 59

**Comment by kinow** [comment]
A few element should be fine. These may be collected later. Or if you have Vue Dev Tools and it's loaded, that extension retains some objects to display.

Or it could be a problem in the code. Looking at the list of retainers should help identify which part of the code is involved (for this, it's better to be in development mode, as otherwise the code is minified, and functions and variables are renamed to things like  `$t()`, `$a`, etc.

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
