### PR TITLE
Update Vuetify to 2.1, along with other dependencies with updates available

### LINKED ISSUE #276: Update to Vuetify 2.1
Vuetify announced the 2.1 release. We recently moved from 1.5 to 2.0. This next update should be much simpler. Change log: https://github.com/vuetifyjs/vuetify/releases/v2.1.0

### PR DESCRIPTION
**Pull request by kinow**
These changes close #276

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why? library update).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Looks pretty much the same to me.

image

Struggled a bit to fix the `Header` component style, and also cleaned up unused values for `Header` and `Drawer`.

**Comment by kinow** [comment]
List of what was updated:


```bash
$ ncu -u


   ╭──────────────────────────────────────────────╮
   │                                              │
   │      Update available 3.1.21 → 3.1.23        │
   │   Run npm i -g npm-check-updates to update   │
   │                                              │
   ╰──────────────────────────────────────────────╯

Upgrading /home/kinow/Development/python/workspace/cylc-ui/package.json
[====================] 50/50 100%

 graphql                       ^14.5.3  →  ^14.5.8 
 tippy.js                       ^4.3.5  →   ^5.0.2 
 vee-validate                   ^3.0.2  →  ^3.0.11 
 vue-i18n                      ^8.14.0  →  ^8.14.1 
 vue-meta                       ^2.2.1  →   ^2.3.1 
 vue-router                     ^3.1.2  →   ^3.1.3 
 vuetify                       ^2.0.10  →   ^2.1.3 
 @mdi/font                     ^4.1.95  →  ^4.5.95 
 @vue/cli-plugin-babel         ^3.11.0  →  ^3.12.0 
 @vue/cli-plugin-e2e-cypress   ^3.11.0  →  ^3.12.0 
 @vue/cli-plugin-eslint        ^3.11.0  →  ^3.12.0 
 @vue/cli-plugin-unit-mocha    ^3.11.0  →  ^3.12.0 
 @vue/cli-service              ^3.11.0  →  ^3.12.0 
 cross-env                      ^5.2.0  →   ^6.0.3 
 eslint                         ^6.2.2  →   ^6.5.1 
 sass                         ^1.22.10  →  ^1.23.0 
 sass-loader                    ^7.3.1  →   ^8.0.0 
 sinon                          ^7.4.1  →   ^7.5.0 
 standard                      ^14.0.2  →  ^14.3.1 
 vue-cli-plugin-apollo         ^0.21.0  →  ^0.21.1 
 vuetify-loader                 ^1.2.2  →   ^1.3.0 
 webpack                       ^4.39.2  →  ^4.41.0 

Run npm install to install new versions.
```

**Comment by kinow** [comment]
Funny, failing on `npm run build`, but that works on my computer. Bumped up to Node 10 LTS

image

But still no luck. Will take a look on Monday.

**Comment by hjoliver** [comment]
(I missed your comment on `npm run build` failing - but it works fine in my environment).

**Comment by kinow** [comment]
The error appears to be `ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.`, which would be: https://github.com/webpack-contrib/sass-loader/issues/760

Related to this part of our updates:

> sass-loader                    ^7.3.1  →   ^8.0.0 

image

@hjoliver successfully reproduced it after deleting my `node_modules` and `dist` folders, then re-running `npm run build`. Tricky issue.

Then, `vue inspect | less` and searching for "sass" revealed the origin of the issue.

image

Whew. At least now it appears to make sense why Travis - thankfully - failed. That may have saved us some issues pre/post next release.

Makes even more sense, I think, that `vuetify-loader` (used by Vuetify) creates projects with a `webpack.config.js` that uses that invalid `data` key: https://github.com/vuetifyjs/vuetify-loader/blob/3a6a2ffcfc4233dbfdd88d549d55e6cea79ef4fb/dev/webpack.config.js#L13

Sooo... easier to just downgrade `sass-loader` back to `^7.3.1` instead of trying to fight with this nasty bug. Will file an issue to `vuetify-loader` telling what happened, in case it helps somebody else :+1:

**Comment by kinow** [comment]
I think one review is enough, tested again, all good with the commands on my environment, Travis happy as well. Merging, thanks!!! :tada:

**Pull request merged**
