### PR TITLE
Allow user to choose default view

### LINKED ISSUE #1036: Configurable default workflow view
A user (this one: https://github.com/cylc/cylc-ui/issues/1035#issue-1250273673 ) wants to be able to make the table view the default view. 

I imagine that would be easy to implement via Preferences, without waiting for full tab layout preservation.

(This might already be covered by another Issue?).

### PR DESCRIPTION
**Pull request by AaronDCole**
These changes close #1036

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Two e2e tests have failed:

```
  1) WorkflowService subscriptions
       -> Dashboard -> Workflows, should contain 2 subscriptions (GScan + Tree):
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `.c-tree`, but never found it. Queried from element: <div#main.lm-Widget.p-Widget.lm-Panel.p-Panel.lm-BoxPanel.p-BoxPanel>
      at Context.eval (webpack:///./tests/e2e/specs/workflowservice.cy.js:51:23)

  2) WorkflowService subscriptions
       -> Dashboard -> Workflows -> Dashboard, should contain 2 subscriptions (GScan + Dashboard):
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `.c-tree`, but never found it. Queried from element: <div#main.lm-Widget.p-Widget.lm-Panel.p-Panel.lm-BoxPanel.p-BoxPanel>
      at Context.eval (webpack:///./tests/e2e/specs/workflowservice.cy.js:64:23)
```

This line:

> Expected to find element: `.c-tree`, but never found it.

Suggests to me that the table view was never opened, perhaps because the table view was opened instead? Maybe table has become the default somehow, might possibly be missing a JSON.parse (that caught me out with the data store work)?

**Comment by oliver-sanders** [comment]
I think we can upgrade this to closes #1036 with the remaining work covered by #662.

**Comment by hjoliver** [comment]
Quick functional review - it isn't working for me!

At first load, the new "default to table view" checkbox is unchecked, but the table view popped up as default.  After that, checked or not, I only get tree view when first clicking on a workflow.

BTW, the tree view should be the built-in default.

**Comment by oliver-sanders** [comment]
@AaronDCole are you still working on this one?

**Comment by AaronDCole** [comment]
> @AaronDCole are you still working on this one?

Hey Oliver, sorry this is extremely late! I haven't been (caught up with SDT/the Gscan PR), but I will tidy it up now.

**Comment by MetRonnie** [comment]
Closing on the assumption this is superseded by #1263 (re-open if not)

**Pull request closed without merging**
