### PR TITLE
aotf: support flow arguments

### PR DESCRIPTION
**Pull request by oliver-sanders**
To accompany https://github.com/cylc/cylc-flow/pull/4739

This allows the "trigger" mutation to be run without providing additional context (i.e. you shouldn't need to go through the mutation editor unless you want to fiddle with the defaults) and performs flow validation client-side.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]

**Comment by dwsutherland** [comment]
I think the UIS might need a PR also, getting the following when default triggering in the UI:
image

The error suggests there's a change to the structure of the result being passed from the scheduler to the UIS.

**Comment by dwsutherland** [comment]
Nevermind, worked when cherry-picking:
https://github.com/hjoliver/cylc-flow/pull/21
onto:
https://github.com/cylc/cylc-flow/pull/4739

**Review by dwsutherland — APPROVED** [review]

**Comment by oliver-sanders** [comment]
(rebased)

**Comment by oliver-sanders** [comment]
Dependent PR merged, going in with two approvals.

**Pull request merged**
