### PR TITLE
Avoid content shift by using a skeleton loader in each cell with the item-count

### LINKED ISSUE #660: Dashboard skeleton loader: page jump
A minor but annoying design problem:

I often go to the Dashboard page with the sole intention of clicking on one of the static links (e.g. preferences or hub), then accidentally hit the wrong link when the real Workflows data suddenly replaces the skeleton, which moves the static links downward.

shot

I wonder if we should:
1. make the loader the exact same height as the data table
   -  (but this might not work depending on what gets displayed under Events at the top right side)
1. or put the static links at the top of the page

Thoughts anyone?

### PR DESCRIPTION
**Pull request by kinow**
These changes close #660 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
Looks good, but I've noticed this method doesn't work properly if you crank the font size up high enough in our Settings page (why do we need that in addition to browser zoom, BTW?)

**Comment by kinow** [comment]
> 
> 
> Looks good, but I've noticed this method doesn't work properly if you crank the font size up high enough in our Settings page (why do we need that in addition to browser zoom, BTW?)

Oh, good catch. I forgot to test after we increase the font size. Back to the whiteboard 😬

**Comment by kinow** [comment]
>Looks good, but I've noticed this method doesn't work properly if you crank the font size up high enough in our Settings page 

@hjoliver I see what you mean now. But that also breaks other parts of our layout, such as the User Profile page itself, GScan, the Toolbar... Let me think how to work around this issue.

>(why do we need that in addition to browser zoom, BTW?)

If you change the zoom level, that affects the whole page, and triggers responsive layout, or mobile version. That may or may not be what the user wants. In my case, I use that feature in some sites as I have (as my wife says) an old man's eyesight. 

That allows users to change the font size without affecting the rest of the layout. But we can disable/remove that feature too if others don't use it :+1: (which unblocks this issue too :rofl: )

**Comment by hjoliver** [comment]
>  But that also breaks other parts of our layout, ...

Yeah, that's why I'm wondering if we really need the ability to change font size independently.

It sounds useful in principle, but it can make the page look ugly, and it's not good if it actually breaks parts of the layout.  Let's see what others think...

**Comment by oliver-sanders** [comment]
> Oh, good catch. I forgot to test after we increase the font size. Back to the whiteboard 😬

Should work with `em`s.

**Comment by hjoliver** [comment]
(Can we do it with `em`s?)

**Comment by kinow** [comment]
On it :+1: just finish some tests with Cylc Flow first, then will start working on this one again.

**Comment by kinow** [comment]
Good ref: https://css-tricks.com/accessible-font-sizing-explained/

**Comment by kinow** [comment]
Fixed with a different approach. Instead of worrying about the height of the element (which could change depending on the `font-size` [which we can use `px` or `em`]) I am using a loader within each row :grimacing: 

That way we have no content shifting, regardless of the font size. Also enabled the loader for the Dashboard table as an extra indicator of the query-loading status :+1:

**Review by hjoliver — APPROVED** [review]
Seems to work well, even at pretty extreme font sizes :tada:

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
