### PR TITLE
Remove retrying and submit-retrying states

### LINKED ISSUE #514: Remove retrying and submit-retrying states
**Describe the bug**

Remove retrying and submit-retrying from `TaskStates` enum. Might be a good idea to look around for any other possible uses too :+1: 

Those states were removed in https://github.com/cylc/cylc-flow/pull/3423

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by kinow**
These changes close #514 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
The checkpoint workflow, used to generate the data for the offline mode uses the retrying state too. So I will need a bit more of time understanding how to rewrite it with an xtrigger (I think that's the replacement).

**Comment by hjoliver** [comment]
> The checkpoint workflow, used to generate the data for the offline mode uses the retrying state too. So I will need a bit more of time understanding how to rewrite it with an xtrigger (I think that's the replacement).

Maybe that's not necessary at this point, until we can represent xtriggers in the UI just use waiting as that is the replacement for retrying in terms of state (it is a waiting task, that is waiting on an xtrigger). So a task that fails and retries several times before succeeding (or failing) will look like this: running -> waiting -> running -> waiting -> succeeded (or failed).

**Comment by kinow** [comment]
@hjoliver 

>Maybe that's not necessary at this point, until we can represent xtriggers in the UI just use waiting as that is the replacement for retrying in terms of state (it is a waiting task, that is waiting on an xtrigger). So a task that fails and retries several times before succeeding (or failing) will look like this: running -> waiting -> running -> waiting -> succeeded (or failed).

:+1: I replaced retrying and submit-retrying by waiting in our tests already. I thought that the [workflow used to generate offline data](https://github.com/cylc/cylc-ui/blob/e2726d375575aa0c7c626ed62939831ca28fb60d/src/services/mock/one/flow.cylc#L60-L78) wouldn't work after the latest changes, and I would have to update it.

But I think you are correct!

But I just tried it, and it executes successfully, producing the JavaScript data for the offline mode :tada: So nothing else to be done here. Thanks!

**Comment by kinow** [comment]
@hjoliver assigning you just in case you have time for a quick review today :grimacing: similar to the other one you reviewed yesterday.

**Review by hjoliver — APPROVED** [review]
:+1:

**Pull request merged**
