### PR TITLE
Update dependencies to fix security vulnerabilities

### LINKED ISSUE #326: Fix serialize-javascript XSS bug (github security)
**Describe the bug**

Reported by GitHub automated security check. It is a regex issue in `serialize-javascript` versions less than `2.1.1`. We do not use this dependency directly, so it is coming via transitivity.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

`npm list | grep serialize-javascript` and check version reported. Then check `npmjs.com` for latest release of dependency affected.

**Expected behavior**

No security issues reported.

**Screenshots**

image

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### LINKED ISSUE #399: Update vue-cli to 4.2.0
**Describe exactly what you would like to see in an upcoming release**

Freshly released, we should be OK to update to this version, as long as `eslint` works with no major changes.

One security issue in `vue ui` (I use this tool every other week to check PR's or deps, but not urgent for us IMHO), and "Optional Chaining & Nullish Coalescing" has been added so that we should be able to use things like `const highTemperature = response.data?.[property]?.high;`, `response?.data?.temperature?.high;`, and `const animationTime = settings.animationTime ?? defaultTime;` (similar to PHP's elvis operator).

**Additional context**

Release notes: https://app.releasly.co/releases/vuejs/vue-cli/4_2_0

Interesting points, besides the security issue:

image

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by kinow**
These changes close #326, close #399 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why? dependencies update).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Quite a few security updates available. Better to update before the 0.2 release - if possible.


```bash
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-ui$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install cytoscape-navigator@2.0.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Cross-Site Scripting (XSS)                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cytoscape-navigator                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cytoscape-navigator > jquery                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/328                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cytoscape-navigator                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cytoscape-navigator > jquery                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/796                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install --save-dev @vue/cli-service@4.2.2  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > copy-webpack-plugin >                     │
│               │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1426                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update jquery --depth 2  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Cross-Site Scripting (XSS)                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cytoscape-panzoom                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cytoscape-panzoom > jquery                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/328                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cytoscape-panzoom                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cytoscape-panzoom > jquery                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/796                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update handlebars --depth 6  to resolve 6 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint-config-vuetify [dev]                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ eslint-config-vuetify > @release-it/conventional-changelog > │
│               │ conventional-changelog > conventional-changelog-core >       │
│               │ conventional-changelog-writer > handlebars                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1316                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1316                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint-config-vuetify [dev]                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ eslint-config-vuetify > @release-it/conventional-changelog > │
│               │ conventional-changelog > conventional-changelog-core >       │
│               │ conventional-changelog-writer > handlebars                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1324                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1324                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint-config-vuetify [dev]                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ eslint-config-vuetify > @release-it/conventional-changelog > │
│               │ conventional-changelog > conventional-changelog-core >       │
│               │ conventional-changelog-writer > handlebars                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1325                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1325                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update webpack --depth 2  to resolve 3 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-babel [dev]                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-babel > webpack > terser-webpack-plugin >    │
│               │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1426                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-eslint [dev]                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-eslint > webpack > terser-webpack-plugin >   │
│               │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1426                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > webpack > terser-webpack-plugin >         │
│               │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1426                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update terser-webpack-plugin --depth 2  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack > terser-webpack-plugin > serialize-javascript       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1426                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > terser-webpack-plugin >                   │
│               │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1426                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update @hapi/hoek --depth 5  to resolve 10 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-babel [dev]                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-babel > @vue/cli-shared-utils > @hapi/joi >  │
│               │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-e2e-cypress [dev]                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-e2e-cypress > @vue/cli-shared-utils >        │
│               │ @hapi/joi > @hapi/hoek                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-eslint [dev]                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-eslint > @vue/cli-shared-utils > @hapi/joi > │
│               │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-unit-mocha [dev]                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-unit-mocha > @vue/cli-shared-utils >         │
│               │ @hapi/joi > @hapi/hoek                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > @vue/cli-shared-utils > @hapi/joi >       │
│               │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-babel [dev]                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-babel > @vue/cli-shared-utils > @hapi/joi >  │
│               │ @hapi/topo > @hapi/hoek                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-e2e-cypress [dev]                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-e2e-cypress > @vue/cli-shared-utils >        │
│               │ @hapi/joi > @hapi/topo > @hapi/hoek                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-eslint [dev]                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-eslint > @vue/cli-shared-utils > @hapi/joi > │
│               │ @hapi/topo > @hapi/hoek                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-unit-mocha [dev]                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-unit-mocha > @vue/cli-shared-utils >         │
│               │ @hapi/joi > @hapi/topo > @hapi/hoek                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @hapi/hoek                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > @vue/cli-shared-utils > @hapi/joi >       │
│               │ @hapi/topo > @hapi/hoek                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1468                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 26 vulnerabilities (10 low, 8 moderate, 8 high) in 44384 scanned packages
  run `npm audit fix` to fix 23 of them.
  3 vulnerabilities require semver-major dependency updates.
```

After `npm audit fix --force`, `npm install` shows no vulnerabilities.

```bash
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-ui$ npm install
npm WARN eslint-config-vuetify@0.4.0 requires a peer of eslint@^5.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-node@8.4.1 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.

added 2 packages from 1 contributor and audited 44464 packages in 16.533s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by kinow** [comment]
Also nothing in `npm audit`.

```bash
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-ui$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 44464 scanned packages
```

**Comment by kinow** [comment]
> in 44464 scanned packages

:eyes:

**Comment by kinow** [comment]
To test, review:

- confirm GitHub actions CI pass
- `npm run build:watch` with the Hub. Check the workflow table, workflows view with some widgets like graph, tree, and mutations. Check that the `/graph/...` and `/tree/...` views also work.

**Comment by kinow** [comment]
GitHub actions failed, because `eslint` got updated, and then the `npm run build` task failed due to some new `console.log` entries. Fixed by telling `eslint` to ignore those entries.

**Comment by hjoliver** [comment]
(CI says "git checkout failed"??)

**Comment by kinow** [comment]
Yeah, first it failed in the `npm run build`. Then I pushed a new commit, and it now keeps failing in `git checkout` :eyes: :confused: 

Ain't this GitHub action checking out a GitHub repository? Thought it would be the less likely part to fail :smile:

**Comment by kinow** [comment]
Alright. Pushed too many commits near the same time, I think, and hit a concurrency bug in github actions.

https://github.com/actions/checkout/issues/23

Fixed in the action v2. So will update this PR in a moment to use that in the workflow instead of v1.

**Comment by kinow** [comment]
Phew. Ready for review now.

**Comment by kinow** [comment]
Two more security issues announced, will update the PR to include the fix for those.

image

**Comment by kinow** [comment]
`npm audit fix` fixed several warnings, but not the `acorn` nor `minimist`. So issue a `ncu` to see what could be update, but after reading the eslint (first one I normally update, as it's less likely to break tests & app) changes and issues, found that the fix is still in the works.

https://github.com/eslint/eslint/issues/13012

Have pushed the changes for other security warnings, but we will have to wait until the other issues reported by GitHub can be fixed.

**Comment by kinow** [comment]
Fixing conflicts.

**Comment by kinow** [comment]
Fixed conflicts, executed `npm audit fix` again, and then `npm audit fix --force` to fix other issues that required major updates. Tested locally, Travis passing too. Ready for review again.

**Comment by wxtim** [comment]
Sorry I left it so long @kinow. Looking cool though and thanks for including me!

**Pull request merged**
