### PR TITLE
Sort GScan workflows by type (first running, then held, then stopped), and then by name.

### PR DESCRIPTION
**Pull request by kinow**
Follow-up of #493 

https://github.com/cylc/cylc-ui/pull/493#issuecomment-691893455

image

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
image

image

image

image

**Comment by kinow** [comment]
Will add one or two commits later, for changelog and tests. Then mark as ready for review.

**Comment by hjoliver** [comment]
Very nice! :tada:

**Review by oliver-sanders — APPROVED** [review]
Nice, looks good, tested as working.

I think it might be best to mix running, held and stopping flows in together as users who have large numbers of similarly named flows may get confused if they are split up into groups.

**Comment by kinow** [comment]
> Nice, looks good, tested as working.
> 
> I think it might be best to mix running, held and stopping flows in together (i.e. just separate active and stopped flows) as users who have large numbers of similarly named flows may get confused if they are split up into groups.

@oliver-sanders I also think so. In my case, out of all workflows, I have 1 that I always keep an eye on (`five`, no surprise), and found it annoying when I had multiple running/held, and had to look for `five` amongst the workflows that were not transparent.

@hjoliver let me know what you think, and I can quickly update the PR before your review :+1:

**Comment by hjoliver** [comment]
I agree, let's go with the mixed approach - just separate active and stopped.

**Comment by kinow** [comment]
> I agree, let's go with the mixed approach - just separate active and stopped.

Thanks @hjoliver . This PR should be updated (code + tests) by tomorrow morning :+1:

**Comment by kinow** [comment]
Rebased, and pushed one more commit where the "running" and "held" workflows are grouped together when sorting in GScan.

Now it looks like:

image

So the three running workflows were displayed in the following order:

- a/b/c
- families2
- five

Then I held a/b/c and five. The order stayed the same, as in the screenshot :+1: 

I prefer this way, as it's easier to find my five workflow :grimacing: soon with mutations I might be able to quickly start or restart it too :tada: eventually might be able to do 100% with the UI, using command line only to start UIS and look at logs.

**Comment by kinow** [comment]
Ready for review @hjoliver

**Review by hjoliver — APPROVED** [review]
Brilliant - thanks @kinow :bouquet:

**Pull request merged**
