### PR TITLE
Remove the unloved footer component.

### LINKED ISSUE #358: lumino: fix vertical overflow
Follow-on to #325 

I think the workflow component (or possibly some interaction of this and the toolbar / footer) is causing the page to overflow vertically. As a result the scrollbar is appearing and some content is cut off. By fiddling about with tabs it is also possible to make the page grow vertically.

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by hjoliver**
These changes close #358

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Does not need tests 

- [x] Appropriate change log entry included.

- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
(Have I missed anything?)

**Comment by hjoliver** [comment]
shot

(No browser scroll bar :grin: )

**Comment by hjoliver** [comment]
For a follow-up PR(s), we should get the space below the lumino panes to behave better; reduce the minimum pane size; and ban vertical stacking beyond the viewport (ping @oliver-sanders - users should use the lumino tabs to keep many views alive, not stack 'em ad infinitum to scroll off the bottom of the browser).

**Comment by hjoliver** [comment]
> Everything looks good, and from your screenshot looks like it worked fine (and no errors in the browser console, or in the terminal console I think?).

Yep, no errors (apart those spewing out of the graph view as usual).

**Comment by oliver-sanders** [comment]
Note this part-addresses #348

**Pull request merged**
