### PR TITLE
Display x-axis in UTC

### PR DESCRIPTION
**Pull request by ChrisPaulBennett**
This pull request fixes this issue
https://github.com/cylc/cylc-ui/issues/1917

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] Changelog entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by hjoliver** [comment]
Sorry I'm late to the party on this issue.

This PR clearly works as advertised, but we probably need to use the appropriate time zone for the workflow, not just assume UTC.

If you're not running NWP or climate science workflows the local timezone is probably preferred, and I don't think you'll want to see analysis view time axes in UTC.

```cylc
[scheduler]
    UTC mode = False  # scheduler log timestamps, defaults to local time via global config
    cycle point time zone = +1300  # cycle point time zone, defaults to UTC
[scheduling]
    initial cycle point = now
    [[graph]]
        P1D = "foo"
[runtime]
    [[foo]]
        script = "sleep $(( RANDOM % 10 ))"
```

For the gantt view time axis, it should be determined by `[scheduler]UTC mode`.

**Comment by MetRonnie** [comment]
I imagine it would be useful to be able to choose the timezone from a dropdown (either workflow cycle point time zone, UTC, or local).

The cycle point time zone for the workflow can be got by adding this to the query:
```diff
 query ganttQuery ($workflows: [ID]) {
+  workflows(ids: $workflows) {
+    timeZoneInfo {
+      hours
+      minutes
+      stringExtended // if needed
+    }
+  }
   jobs(live: false, workflows: $workflows) {
     ${jobFields.join('\n')}
   }
 }
```

N.B. the UTC mode setting is not exposed in the GraphQL schema at the moment

**Review by oliver-sanders — COMMENTED** [review]
Tested as working.

It would be good to change the x-axis label to "Time (UTC)" to make this clear.

**Comment by hjoliver** [comment]
> N.B. the UTC mode setting is not exposed in the GraphQL schema at the moment

Hmmm yeah you're right. That's a problem, because cycle point time zone is not what we need for the gantt time axis - which applies even for integer cycling. If you set scheduler `UTC mode` to local time, that's because you want scheduler events logged in local time, which implies you'll also want to see said events in local time in the gantt view.

I guess for now we can just hardwire UTC - because most of our users do NWP and climate workflows - and post an issue to fix it in the future.

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
