### PR TITLE
cylc-pause: change held->paused

### PR DESCRIPTION
**Pull request by oliver-sanders**
Companion to https://github.com/cylc/cylc-flow/pull/4076

> **tldr:** We have separated the concepts of holding workflows and holding tasks within workflows.
>
> * Holding and releasing workflows is now play/pause.
> * Holding and releasing tasks is now hold/release.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (unit and/or functional).
- [x] No change log entry required (unreleased)
- [x] No documentation update required.

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Code looks ok, but e2e build failed on GH

**Comment by kinow** [comment]
Got the e2e almost all passing now, will push a commit to your branch @oliver-sanders :+1:

**Review by kinow — APPROVED** [review]
CI passing. @oliver-sanders do we need to wait for the cylc-flow PR? Maybe because of the workflow state enum change, as I think GScan wouldn't know which icon to display for held state?

**Comment by oliver-sanders** [comment]
Thanks @kinow, wake up in the morning and the tests are fixed!

Yes, should wait for the cylc-flow PR but that should be going in very soon.

**Comment by oliver-sanders** [comment]
Done https://github.com/cylc/cylc-flow/pull/4076

**Pull request merged**
