### PR TITLE
Fix e2e tests

### PR DESCRIPTION
**Pull request by kinow**
Part of #170 

Should fix our old e2e tests. We don't have any screen complete and ready for a test. The ones we have right now are going through changes to match with the design sketch.

The only two tests in our e2e battery are one for the Dashboard, and one for the User Profile views. These tests are simply looking for some text in the page once it is loaded.

This used to work, but got broken after some work on `master`. These tests are not executed on Travis CI for now.

Note: removed the test for `Graph.vue` as that was empty and not doing any assertion now (cc @MartinRyan :+1: )

### CODE REVIEW

**Comment by kinow** [comment]
De-conflicted.

**Comment by kinow** [comment]
Rebased.

**Comment by oliver-sanders** [comment]
Looks good, could you rebase this to make sure they still pass after recent merges.

**Comment by kinow** [comment]
>Looks good, could you rebase this to make sure they still pass after recent merges.

Good idea. Tested locally.

1. rebased onto `master`
2. `npm install` OK
3. `npm run lint` OK
4. `npm run test:unit` OK
5. `npm run test:e2e -- --headless` OK

Pushing the rebased branch now so Travis can double check this (except e2e, which is not yet rigged in Travis).

**Pull request merged**
