### PR TITLE
Fix toolbar toggle button color not changing

### PR DESCRIPTION
**Pull request by MetRonnie**
Partial revert of 74670c0fff9ad1b52c583d0cc21c58a9de67a843

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] No docs needed

### CODE REVIEW

**Comment by oliver-sanders** [comment]
"toolbar toggle button"?

**Review by oliver-sanders — APPROVED** [review]
These things need to remain reactive then?

**Comment by MetRonnie** [comment]
I haven't reasoned why but yes it seems so

**Comment by oliver-sanders** [comment]
Taking a peek, I expect it's the `value` fields which makes sense.

**Pull request merged**
