### PR TITLE
Show Cylc object ID, type and status at top of mutations menu

### LINKED ISSUE #769: Ideas for improving the tree view
**Describe exactly what you would like to see in an upcoming release**
- [ ] A tooltip that appears when you hover over a task's state icon, telling you what the state is in case you don't know what the icon means
  - E.g. I wasn't sure what the icon meant here with the dot outside the circle (it means runahead)
  
    image

- [x] (#805) A "pill" type annotation next to the workflow run name, showing the state of the workflow, whether it's "running", "paused", "finished", "stopped - REQUEST(CLEAN)" etc. I know this is already in the Gscan, but it might be useful to have on the tree view page too.
  - Quick mockup (modified GitHub UI in devtools):
  
    image

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes close #769 

Show the task/job/cycle/workflow ID, type and state at the top of the mutations menu (or just that alone if the object doesn't have a mutations menu)

Not sure how to write a test for this

#### Screenshots

---

#### Requirements check-list
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

#### Also to do:
- [ ] Update [wiki entry for `v-cylc-object` directive](https://github.com/cylc/cylc-ui/wiki/Directives)

### CODE REVIEW

**Comment by MetRonnie** [comment]
> Not entirely nice if users make task names very long

- Reduced font size of object ID title
- Set max width of 600px for mutations menu

**Comment by MetRonnie** [comment]
Mobile view (iPhone SE size)

**Review by wxtim — APPROVED** [review]
Happy with your response to my review comment. :)

**Review by hjoliver — APPROVED** [review]
LGTM

**Pull request merged**
