### PR TITLE
menu drawer hidden when in responsive mode (issue 183)

### PR DESCRIPTION
**Pull request by MartinRyan**
changes to graph z-indexes to show menu drawer when in responsive mode

### CODE REVIEW

**Comment by kinow** [comment]
Small change, but should fix it. Will test it later (currently debugging something in cylc-ui). @MartinRyan any chance to squash the commits... github UI shows 7 commits...

**Comment by hjoliver** [comment]
Yes, please tidy up the branch history @MartinRyan - it's just a bunch of merge commits.

**Comment by hjoliver** [comment]
Easy way is:
- update your master
- then on this branch, `git rebase master`

(Rebase will automatically squash all the content-free merge commits)

**Comment by MartinRyan** [comment]
couldn't get rid of that last merge commit, their was a conflict with master that needed resolving

**Comment by kinow** [comment]
>couldn't get rid of that last merge commit, their was a conflict with master that needed resolving

Looking better than before, approving. Thanks!

**Pull request merged**
