### PR TITLE
Rename suite to workflow

### LINKED ISSUE #73: Rename Suite to Workflow
To match the new naming conventions in Cylc 8. This will be a relatively major change, so not doing it with the GraphQL pull requests (#71 #70 )

### PR DESCRIPTION
**Pull request by kinow**
Close #73 

Replaces old use of Suite by Workflow (new nomenclature in Cylc 8).

The unit tests and coverage numbers will go down, but I will write some unit tests for the current code later :+1: 

Tested locally with `npm run` and commands to build/lint/run. The mocked data works with no issue.

- i18n files are renamed to Workflow
- Old `Suites.vue` is replaced by `GScan.vue`, which was giving pretty much the same information
- Old `Suite.vue` is replaced by `Tree.vue`, which was giving same information, without the table (no vue-ads-table component, and using Job and Task new components)
- `SuiteService` has been replaced by `WorkflowService`

Most of the hard work was done by @oliver-sanders , as his components and new views and other changes were all using the correct new term (thanks!).

Bruno

### CODE REVIEW

**Comment by kinow** [comment]
(Note: there is a link to "Workflows" now, but that will be replaced yet again, once we have the `GScan` component working as expected, replacing the links on the left menu as in the design sketches :+1: )

**Comment by kinow** [comment]
And just finished testing manually, with `cylc-ui` + `cylc-uiserver`, with suite `five` running. UI working as expected - as far as I could tell. Ready for review if no errors pop up in Travis.

**Comment by kinow** [comment]
Almost forgot to remove the VueAdsTableTree component. Done, and fixed one warning from the browser console.

**Comment by oliver-sanders** [comment]
The unit tests and coverage numbers will go down, but I will write some unit tests for the current code later +1

:+1:

**Comment by kinow** [comment]
Thanks @oliver-sanders ! Anyone volunteer as second reviewer?

**Comment by wxtim** [comment]
Someone didn't press `ctrl`+`F5`.

**Pull request merged**
