### PR TITLE
Remove unnecessary dev dependencies

### PR DESCRIPTION
**Pull request by MetRonnie**
This is a small change with no associated Issue.

- autoprefixer
- postcss
- regenerator-runtime
- zen-observable

Autoprefixer & postcss seem to be included with vue-cli-service, so no need for a direct dependency. https://cli.vuejs.org/guide/css.html#postcss

I have checked:
- `yarn install`
- `yarn build`
- Looked at `dist/css` to see that vendor prefixes are still present

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests 
- [x] No change log entry required
- [x] No documentation update required.

### CODE REVIEW

**Comment by MetRonnie** [comment]
Ah but is `postcss` actually used anywhere?

**Comment by oliver-sanders** [comment]
That's a different question and I don't know.

**Comment by oliver-sanders** [comment]
`postcss` is *not* listed as unused by `depcheck`. We have `./postcss.config.js` dunno if it's actually used. It doesn't look like we are using any of the patterns in the usage - https://github.com/postcss/postcss#usage

**Comment by MetRonnie** [comment]
Both were added in https://github.com/cylc/cylc-ui/commit/6480ea2f0dadc759345f382a3d53d561b3a49925

But according to https://cli.vuejs.org/guide/css.html#postcss, postcss is used internally by vue-cli-service and the autoprefixer is enabled by default. Tests and build working

**Comment by oliver-sanders** [comment]
I tried injecting errors into that postcss file on master and couldn't get an error out of it so certainly looks like it's unused.

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
