### PR TITLE
yarn up

### PR DESCRIPTION
**Pull request by oliver-sanders**
This includes the current crop of dependabot and renovate PRs followed by `yarn up -R '*'`.

The security label comes from this PR: https://github.com/cylc/cylc-ui/pull/1486

Please perform a functional review to test for breakages.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by wxtim** [comment]
Nice - had a good poke around - quite like the fact that the graph iQL editor picked up my dark theme preference. That seems a lot slicker in general. The only bug is that for me the tooltips on the buttons in the editor don't stay open more than 1/4 second (I had to use dev tools to read them). Happy to pass over this, so I'm approving. Merge if you don't want to address that.

**Review by wxtim — APPROVED** [review]

**Comment by wxtim** [comment]
> > The only bug is that for me the tooltips on the buttons in the editor don't stay open more than 1/4 second (I had to use dev tools to read them)
> 
> Is that in GraphiQL or Cylc UI?

GraphiQL - hence being prepared to ignore it.

**Comment by oliver-sanders** [comment]
That's fine (not our problem), so long as it's still functional, and, more importantly the cylc-ui app is working well.

**Comment by oliver-sanders** [comment]
(if so, whack merge)

**Pull request merged**
