### PR TITLE
Fix leaf and other tree nodes layout.

### LINKED ISSUE #387: treeview leaf (job data) layout tweak
Response to tab width isn't ideal.
- "latest message" breaks very early
- all data keys break on space
- final (narrowest) position has text overlap (including on the job icon row above the leaf)

peek-leaf

### LINKED ISSUE #394: Tree: don't split between task icon and name
Minor issue; affects long task names and/or narrow tab widths:

shot

### PR DESCRIPTION
**Pull request by kinow**
Especially when the user resizes the browser window, reducing the view port. Now
we are using CSS flex and setting nowrap where applicable.

These changes close #387 , and close #394 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why? css changes, although they could be tested with e2e).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Have it working locally, but with one problem that occurs only when used with Lumino.

When you resize the widgets, the flex div may get the wrong `width`. Trying to find a solution for that now.

image

**Comment by kinow** [comment]
2020-01-31 12-57-41 flv

**Comment by kinow** [comment]
@hjoliver just found one minor issue now, but almost ready for review. Just a sec.

**Comment by kinow** [comment]
Ready for review! :tada: 

It was fun. Had an issue with the flex elements and the width of the elements with Lumino. Fixed by using `display: table` (after experimenting with pretty much every other possible value :smile: ).

Tested on Win10Pro chromium and Ubuntu Firefox.

2020-01-31 16-10-55 flv

**Comment by kinow** [comment]
Moved to 0.2

**Comment by hjoliver** [comment]
One review will do for this.

**Pull request merged**
