### PR TITLE
cypress: upgrade from V3 to V6

### PR DESCRIPTION
**Pull request by oliver-sanders**
I've been getting a really old Cypress V3, not sure if that was on-purpose.

Trying to get Cypress to pick up my installed browser I bumped it to V6 which kinda worked in that it picked up my browser, but I then get "Whoops, we can't run your tests". Progress is getting a different error ...

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
No reason to stay on V3, let's just sort out this build and upgrade to V6 or newer :+1:

**Comment by kinow** [comment]
Reading the diff here surprised me a bit that we had no entry for cypress in `package.json`. My bad :smile: 

The current V3 comes via transitive dependency to `vue/cli-plugin-e2e-cypress`

```
$ yarn list | less
(...)
├─ @vue/cli-plugin-e2e-cypress@4.5.9
│  ├─ @vue/cli-shared-utils@^4.5.9
│  ├─ cypress@^3.8.3
│  └─ eslint-plugin-cypress@^2.10.3

```

Hopefully these cypress related libraries we have in our stack are compatible with V6.

**Review by kinow — COMMENTED** [review]
Reading the diff here surprised me a bit that we had no entry for cypress in `package.json`. My bad :smile: 

The current V3 comes via transitive dependency to `vue/cli-plugin-e2e-cypress`

```
$ yarn list | less
(...)
├─ @vue/cli-plugin-e2e-cypress@4.5.9
│  ├─ @vue/cli-shared-utils@^4.5.9
│  ├─ cypress@^3.8.3
│  └─ eslint-plugin-cypress@^2.10.3

```

Hopefully these cypress related libraries we have in our stack are compatible with V6.

**Comment by kinow** [comment]
Unit tests job failed due to checksum error for Cypress binary :confused: kicked GH actions.

**Comment by kinow** [comment]
The `yarn install`, and commands `lint` and `test:unit` both worked fine for me. No idea why GH actions is complaining about checksum... it appears to be trying to install Cypress 3 even though we upgraded it.

Now the `yarn run test:e2e` in my environment failed. There are minor issues, that appear to be due to updated libraries. Things like `expect(cy.get('.v-alert))..should('not.be.visible')` worked before, but now is failing due to `cy.get('.v-alert')` not finding the element.

There are minor changes required I think for the e2e tests to pass. I think the hardest will be to understand why it's installing V3 and failing to verify the checksum.

```
Directory: /home/runner/work/cylc-ui/cylc-ui/node_modules/@vue/cli-plugin-e2e-cypress/node_modules/cypress
Output:
Installing Cypress (version: 3.8.3)

25l[19:58:24]  Downloading Cypress     [started]
[19:58:27]  Downloading Cypress     [failed]
25hThe Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.8.3?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: e7e56af56eb698723f81aff1f0ef7cac4927c3e16c7ea17af7da28933aace2b1bdb5de9474e615e8742c3ae95bfd29de6cde722ed9bbf9d1250a402fac56a493
Computed checksum: d7919d26c9a3e1b1b6e6cce755e7e771c291c318cadd6a0897efbaa0c9722db0a35c5d8bd5effc27994e6d3708e162a3665950fb228bf41193bf678360656a6d

Expected downloaded file to have size: 166901671
Computed size: 203515894
```

:confused:

**Comment by oliver-sanders** [comment]
> The current V3 comes via transitive dependency to vue/cli-plugin-e2e-cypress

> Hopefully these cypress related libraries we have in our stack are compatible with V6.

Yes, that had me confused for a while.

**Comment by oliver-sanders** [comment]
I've taken a look at the tree tests, looks like the `.leaf` nodes don't exist in the DOM?

```
document.getElementsByClassName('.leaf')
HTMLCollection []length: 0__proto__: HTMLCollection
```

Adding a `.should('exist')` check reveals this.

**Comment by oliver-sanders** [comment]
Looks like the same story with other tests reporting missing elements.

**Comment by kinow** [comment]
We may need a [selective resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) for the Cypress dependency, as that Vue dependency appears to be trying to install V3. We have one already for a Istanbul dependency.

Maybe this:

```diff
diff --git a/package.json b/package.json
index 6d2d57ef..fc4df4da 100644
--- a/package.json
+++ b/package.json
@@ -94,7 +94,8 @@
     "webpack": "^4.44.2"
   },
   "resolutions": {
-    "istanbul-instrumenter-loader/**/istanbul-lib-instrument": "4.0.1"
+    "istanbul-instrumenter-loader/**/istanbul-lib-instrument": "4.0.1",
+    "cypress": "^6.1.0"
   },
   "bugs": {
     "url": "https://github.com/cylc/cylc-ui/issues"
```

**Comment by oliver-sanders** [comment]
Hmmm, took a quick look at `@vue/cli-plugin-e2e-cypress`, it's a tiny project with 0 stars or forks with an old Cypress dependency

Perhaps we should consider chaning library, @cypress/vue brings in a much more contemporary `5.6.0`.

**Comment by kinow** [comment]
> Hmmm, took a quick look at `@vue/cli-plugin-e2e-cypress`, it's a tiny project with 0 stars or forks with an old Cypress dependency
> 
> Perhaps we should consider chaning library, @cypress/vue brings in a much more contemporary `5.6.0`.

Sounds like a good plan. I think I added that from some tutorial when we started creating Cylc UI. There may be other libraries related to vue-test-utils & Cypress that can/need to be updated here too :+1:

**Comment by kinow** [comment]
Tried to switch to `@cypress/vue`. The `yarn run test:e2e` is handled by vue-cli and the old plug-in, so that command doesn't work. Running `yarn run test:cypress`, Cypress starts, but is unable to run the existing tests.

Installed some extra dependencies, but did not manage to get the existing tests to pass :cry: I probably just need a bit more of time. The `@cypress/vue` appears to be under development, and with Vue 3 I wonder if they finished everything for Vue2 + Cypress, or if the development moved to support Vue3 + Cypress :thinking: 

>The Cypress Component Testing library is in still in Alpha. We are rapidly developing and expect that the API may undergo breaking changes. Contribute to its development by submitting feature requests or issues

**Comment by oliver-sanders** [comment]
Couldn't get it to work at my end either, hopefully will get it working one day

**Comment by kinow** [comment]
@oliver-sanders I dug a bit deeper looking for an explanation why CI was failing with this new version of Cypress. From what I understood, after reading comments in Cypress issues, the issue is caused by other dependencies that are using older versions of Cypress.

Even though we are defining version 6.x in the `devDependencies`, yarn (and looks like npm too) gets confused with the other versions, and fails to compare checksums (it's like it's getting the computed checksum of 6.2.1 and comparing against the fetched checksum of some version 3.x).

So I've added a `resolutions` entry, which prevents yarn of using other versions but the one we defined in `devDependencies`.

That fixed the CI issue, but the new version of Cypress appears to cause existing tests that were passing, to now fail. These tests were using `.should('not.be.visible'`) (or `be.visible`). Again found multiple comments on GitHub issues, and also in StackOverflow answers, saying that `should('not.exist')` should now be used.

So I've updated the tests, and everything worked locally, and in GH actions for my fork. Now waiting for CI to finish here (I pushed a couple commits with these fixes to this branch, hope it's OK :+1: ).

**Review by kinow — APPROVED** [review]
To confirm the version, listed dependencies via `yarn list` (other versions too, but the 6.2.1 is closest to the root of the dep tree, and also in the resolutions list), and also did the `npx cypress -version`.

```bash
kinow@ranma:~/Development/python/workspace/cylc-ui$ npx cypress -v
Cypress package version: 6.1.0
Cypress binary version: 6.1.0
Electron version: 11.0.2
Bundled Node version: 12.18.3
```

Couldn't get `yarn run test:cypress` to work, but I had never used before. To run e2e tests locally, I've always used `yarn run test:e2e`, which is used by CI and is working both locally and in the CI.

+1

**Comment by kinow** [comment]
Will leave it up to @oliver-sanders to review my comments & code too, and either assign a second reviewer or merge if it's looking OK.

**Comment by oliver-sanders** [comment]
> Couldn't get yarn run test:cypress to work, but I had never used before

This was a dodgy alias I had added to launch cypress, because it wasn't a top-level dep you couldn't just do `yarn run cypress` but now you can!

**Comment by oliver-sanders** [comment]
Tested on MacOS and Linux, this fixes issues I was getting with spontaneous test failures which was making it very hard to write functional tests (some issue between older cypress and MacOS presumably).

**Comment by oliver-sanders** [comment]
Hmmm, had problems compiling for edge on Windows, trying MacOS.

**Comment by oliver-sanders** [comment]
Safari support may be coming to Cypress one day, added a blocked issue to track this - https://github.com/cylc/cylc-ui/issues/569

**Comment by oliver-sanders** [comment]
Edge build now passing on MacOS, looks like our build toolchain is not Windows compatible, not important, Edge support is now tested.

**Comment by kinow** [comment]
> Hmmm, had problems compiling for edge on Windows, trying MacOS.
> 
> ```
> Oops...we found an error preparing this test file:
> 
> e2e\support\index.js
> 
> The error was:
> 
> Error: EINVAL: invalid argument, mkdir 'C:\Users\runneradmin\AppData\Roaming\Cypress\cy\production\projects\cylc-ui-0520bf890395809b76166d59378edb72\bundles\tests\e2e\support\D:\a\cylc-ui\cylc-ui\dist'
> ```
> 
> https://github.com/cylc/cylc-ui/runs/1687331027?check_suite_focus=true#step:3:4211

The Windows build error is caused, apparently, by the Cypress webpack preprocessor: https://github.com/cypress-io/cypress/issues/6441

Looks like it's not handling aliases correctly.

**Review by kinow — APPROVED** [review]
Re-approving, now with MacOS + Edge! :tada:

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
