### PR TITLE
Fix icons in the Dashboard

### PR DESCRIPTION
**Pull request by kinow**
This is a small change with no associated Issue.

Fixing issue reported by @hjoliver on Element, where he would get the icons in the dashboard with a really large width/height. I reproduced the issue, but instead of large icons, my dashboard had no icons at all.

From what I could tell, something might have changed in Vuetify, where the parent element VList or VListItem stopped giving the right dimensions, and instead returned large or invalid values, causing the icon—which inherits the height and widget—to be either very large or hidden.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
No change in coverage, but one test added. It is now checking `be.visible` of the first icon in the `.c-dashboard` panel. It uses JQuery to check the visibility.

**Comment by hjoliver** [comment]
Is there any problem with hardwire the size to 24 here, as opposed to the mysteriously-broken "medium"?

**Comment by kinow** [comment]
> Is there any problem with hardwiring the size to 24 here, as opposed to the mysteriously-broken "medium"?

Good question. The default value is 24: https://github.com/vuetifyjs/vuetify/blob/5a39a01de42809157b026cff81ad63e2637661a8/packages/vuetify/src/components/VIcon/VIcon.ts#L20

But they could change it too. The medium size was 28. In my IDE, there's no `medium` directive. Only `x-small`, `small`, `large`, and `x-large`. I think it might be related to this bug: https://github.com/vuetifyjs/vuetify/issues/12168, fixed (not sure if released).

So I think we can either use a fixed size like `24`, `28`, or use the `large` value for now? What do you think @hjoliver ? 

Untitled

(image showing the `large` directive replacing `medium`)

**Comment by hjoliver** [comment]
I vote for large - it looks fine

**Comment by kinow** [comment]
Looks good to me too. Will try on mobile/responsive modet o confirm it is still proportional and then update this PR.

**Comment by kinow** [comment]
Working on large and smaller screens. Edited commit, ready for review again :+1:

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
