### PR TITLE
fix deps

### PR DESCRIPTION
**Pull request by wxtim**
closes:
- ~#949~ Replaced by https://github.com/cylc/cylc-ui/pull/984
- ~#950~ Replaced by https://github.com/cylc/cylc-ui/pull/985
- ~#951~ Reopened
- ~#956~ Reopened
- #957 
- #958 
- ~#959~ Replaced by #971 

draft pending fixing some issues with building locally.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (dependency update).
- [x] No documentation update required.

### CODE REVIEW

**Comment by MetRonnie** [comment]
What is the status on this? Probably best to reopen those dependabot PRs if this is not going ahead

**Comment by wxtim** [comment]
> What is the status on this? Probably best to reopen those dependabot PRs (adding [ blocked](/cylc/cylc-ui/labels/blocked) as appropriate) if this is not going ahead

I'll do it. Sitting watching yarn is fine.

**Comment by MetRonnie** [comment]
Seems to work, however I am not sure about upgrading the vue-cli plugins, it seems it should be done when upgrading the vu-cli-service to v5: https://cli.vuejs.org/migrations/migrate-from-v4.html. Asking Oliver

**Comment by oliver-sanders** [comment]
> Asking Oliver

Not sure but I would definitely suggest using the vue commands to manage the plugins.

**Comment by wxtim** [comment]
I've tried to re-open the PRs this one is trying to consolidate, but dependabot has closed them again.

**Comment by MetRonnie** [comment]
Looks like dependabot created new PRs to supersede (probably because even newer versions have come out since)

**Pull request closed without merging**
