### PR TITLE
Simplify mutation menu

### PR DESCRIPTION
**Pull request by MetRonnie**
By figuring out how to use `VMenu` better I was able to drop a fair amount of cruft.

We were originally using `VMenu` but through various attempts to get it to behave the way we want (e.g. #927, #1269) I ended up re-implementing some of the behaviour manually (e.g. click-outside behaviour).

It turns out the key to using `VMenu` and getting it to behave the way we want is not too difficult:
- `:target` prop - this allows Vuetify to take care of positioning relative to the `c-data-interactive` element that was clicked on
- `:key` prop - this allows the menu to re-open when clicking between `c-data-interactive` elements  by using a unique identifier for each element (so Vue knows a different element has been clicked)

Update: also renamed the `v-cylc-object` directive to `v-command-menu` as that is more descriptive IMO

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Tests are included 
- [x] `CHANGES.md` entry not needed as invisible to users

### CODE REVIEW

**Review by oliver-sanders — COMMENTED** [review]
Looks good to me.

Spotted one issue in the graph view where opening the menu on different jobs didn't behave as elsewhere. Haven't checked this against master, however, it appears to be fixed with #1780

**Comment by MetRonnie** [comment]
https://github.com/cylc/cylc-ui/compare/2309827454a7782fab1888be0f2c4b9c8d6370ea..e5363541968df64c5fa872544717cb5acbfbafae should make it immune to that kind of thing

**Comment by oliver-sanders** [comment]
Fixed.

**Review by oliver-sanders — APPROVED** [review]

**Comment by MetRonnie** [comment]
@markgrahamdawson Tagged you for review. If you've not come across the mutation menu code before, it might be best for me to explain how it works before you review

**Comment by MetRonnie** [comment]
I've also renamed `v-cylc-object` to `v-command-menu` as that is more descriptive IMO

**Review by markgrahamdawson — APPROVED** [review]

**Review by oliver-sanders — APPROVED** [review]
I found one "quirk" when a task disappears from the n-window and is removed from the view, any open menu will jump to the top-left of the screen (because the target node has been removed).

Would be beneficial if we could disable this behaviour, but the menu remains functional so not a biggie.

**Pull request merged**
