### PR TITLE
Update dependencies (especially @apollo/client)

### PR DESCRIPTION
**Pull request by kinow**
This is a small change with no associated Issue.

I follow @apollo/client, @vue/vue, and the vuetify repos for updates as they are probably our most important dependencies. @apollo/client 3.2.0 was released today/last night: https://github.com/apollographql/apollo-client/releases/tag/v3.2.0

This PR bumps up other dependencies too, and more importantly, it removes vue-apollo-plugin. Which looks like it was bringing old apollo dependencies transitively :angry: 

Fixed the imports to use only `@apollo/client`. Which is good, as we only ever need to maintain 1 dependency (`@apollo/client`) instead of multiple (1 for apollo-client, 1 for the ws-link, 1 for apollo-utilities, etc).

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
Did you mean to delete `yarn.lock`?

**Comment by kinow** [comment]
> Did you mean to delete `yarn.lock`?

I think it looks like the file was deleted, but it's mainly deleted lines in GitHub UI. So there should be several red squares, and the diff is suppressed due to the number of changes.

Clicking on expand and then to display the changes should show what was removed (most changes should be related to the removal of vue-apollo plug-in, taking away several dependencies related to apollo-client, now grouped together in `@apollo/client`).

**Comment by hjoliver** [comment]
You're right (duh! :confounded: ) - so many deletions (vs additions) I just assumed the whole file was removed.

**Review by oliver-sanders — APPROVED** [review]
Looks ok, tests pass.

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
