### PR TITLE
Move to GitHub Actions

### LINKED ISSUE #321: Migrate to GitHub actions
**Describe exactly what you would like to see in an upcoming release**

Hi, some time ago I mentioned GitHub Actions in a issue of Cylc Flow ([link](https://github.com/cylc/cylc-flow/issues/3046#issuecomment-479664098)). Cylc Flow is the most complex project build we have in the Cylc organization.

GitHub actions has at least one advantage, the checkout time must be better I reckon. But I would like to experiment with GitHub actions, and see if others agree to move the other projects too (before we tackle issues like [remote tests in Cylc UI](https://github.com/cylc/cylc-flow/issues/3429)).

Cylc UI is the project I am more familiar with, and have a better idea of how the build process works, and how long it normally takes.

**Additional context**

Our build in Travis CI for Cylc UI takes around **`~7m 30s`**.

image

The first build at the top happened at the same time of another build on GitHub actions.

image

The build on GitHub actions took half the time of the build on Travis for the same PR, just **`3m 41s `**.

Note, that **I had not enabled cache**. `npm install` normally takes a long time. It took almost 2 minutes to run `npm install` on GitHub infra.

image

Then I added two more commits. The first new commit was based on the [actions docs for caching](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows), using their npm example (without restore_keys, simply caching based on the `package-lock.json` hash). This commit took about the same time to build (1 second difference **`3m 42s`**).

The second commit was to modify the badge, and also to verify how much faster it was after using caching. The build took **` 1m 37s`** :tada: :confetti_ball: .

image

Finally, I pushed one more commit, to remove `.travis.yml`. Again, one second difference.

image

One downside is that GitHub actions is a newer product. I used it during the beta, and there were several features missing, the interface was also a bit buggy. But now after 2 months I think, there are lots of documentation. Apparently several users have adopted it already. It has pretty much the same functionality as Travis free for Open Source (not sure about $$$ plans). And also looks like their infrastructure is faster for builds, at least for builds of JS projects.

ps: the `git clone` in Travis took 1.01 seconds, and `npm install` 77.05 seconds. Same commands in GitHub actions took 2 seconds (weird, longer on GitHub? Or maybe that's because Travis does a `--depth=50`? Not sure what GitHub action does, we are using their default checkout action), and 19 seconds.

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by kinow**
These changes close #321 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why? build scripts only).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Draft as not sure if others will agree with the move - it would probably mean moving other projects to GitHub Actions too. Took me around 10 minutes to prepare the workflow in GitHub (I've seen people using actions, build, workflows, etc... the docs of github actions use workflows too), and another 30-40 minutes to test caching and write ticket and prepare the PR.

Shouldn't take long for cylc-uiserver and smaller projects. Probably will take a couple of days or a bit more for Cylc Flow due to functional tests. But it would allow us to use Docker containers and actions. Which, if faster on GitHub, would be a huge advantage (Docker containers can be slow to start up and provision/install required software depending on the infra).

**Comment by hjoliver** [comment]
I don't see any reason not to do this; let's make a decision in the meeting on Tuesday.

**Comment by kinow** [comment]
Ready for review.

**Comment by kinow** [comment]
Thanks @hjoliver !

Your merge here has triggered the first GitHub action :-) 

https://github.com/cylc/cylc-ui/actions?query=workflow%3ACI

I have disabled the push-trigger in Travis for cylc/cylc-ui (those two options under the General text)

image

**Comment by kinow** [comment]
(first action took 3m57s, better than 7m30s from travis, but hope it will be even better now with the cache ready)

**Pull request merged**
