### PR TITLE
Toolbar play from stopped

### PR DESCRIPTION
**Pull request by oliver-sanders**
built on #805

This completes the play-pause/resume-stop sequence in the workflow toolbar.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Appropriate tests are included (unit and/or functional) - hard to test with mocked data
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Testing this sort of thing without live data is going to be a bit tricky/limited, can have a go, will take a look next week.

Long term I think a system integration test suite for cylc-flow, cylc-uiserver and cylc-ui with Cypress might be a good way to go.

Would be good to slide this into the beta if possible so may need to go on manual testing for now and bump to an issue.

**Comment by oliver-sanders** [comment]
Rebased, added changelog.

**Review by hjoliver — APPROVED** [review]
LGTM

**Review by datamel — APPROVED** [review]
I have checked out the branch and tested the change. Looks great, thanks @oliver-sanders. 
The change is not covered by a test, like you said it is a hard one to test and I'm not quite sure how I would go about it so I am merging having manually tested, I could open an issue for the testing if you think it would be fitting?

**Comment by oliver-sanders** [comment]
I think we have an issue on cylc-admin for system testing.

My best idea ATM is to use Cypress to test the UI but using live data provided by a UIS.

**Pull request merged**
